#!/bin/bash
echo "🆔 Creating new projectId for @liovyued/mytrainpro..."
echo ""
echo "Please run the following command manually in your terminal:"
echo ""
echo "cd mobile"
echo "npx eas init"
echo ""
echo "When prompted:"
echo "1. Answer 'Y' to create a new project"
echo "2. The project will be created as @liovyued/mytrainpro"
echo "3. A new projectId will be automatically added to app.json"
echo ""
echo "After running eas init, you can then build with:"
echo "EXPO_NO_CAPABILITY_SYNC=1 eas build --platform ios --profile production"
echo ""
echo "Note: Make sure you have Apple Developer access for account 'liovyued'"