-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWC7ThvvSNczov+Hg
6/QA86TFZFFxL5cPrhvePbv2QHigCgYIKoZIzj0DAQehRANCAASpAZhxGikPr+AL
WsZJ287TO4hHQ55hSynSIjOXkrnswsBevPV3r2YEHeQqINIaP4pclAwt/ePMRZoa
Uzf6SKAh
-----END PRIVATE KEY-----