import { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "es" | "ja" | "zh-CN" | "de" | "zh-TW";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translation map
const translations: Record<Language, Record<string, string>> = {
  en: {
    "dashboard": "Dashboard",
    "nutrition": "Nutrition",
    "training": "Training",
    "reports": "Reports",
    "profile": "Profile",
    "calories": "Calories",
    "protein": "Protein",
    "carbs": "Carbs",
    "fat": "Fat",
    "goal": "Goal",
    "current": "Current",
    "log_food": "Log Food",
    "start_workout": "Start Workout",
    "weight": "Weight",
    "sets": "Sets",
    "reps": "Reps",
    "rest": "Rest",
    "completed": "Completed",
    "save": "Save",
    "cancel": "Cancel",
    "submit": "Submit",
    "loading": "Loading...",
    "welcome": "Welcome to TrainPro",
    "sign_in": "Sign In",
    "sign_up": "Sign Up",
    "email": "Email",
    "password": "Password",
    "name": "Name",
    "language": "Language",
    "theme": "Theme",
    "light": "Light",
    "dark": "Dark"
  },
  es: {
    "dashboard": "Panel",
    "nutrition": "Nutrición",
    "training": "Entrenamiento",
    "reports": "Informes",
    "profile": "Perfil",
    "calories": "Calorías",
    "protein": "Proteína",
    "carbs": "Carbohidratos",
    "fat": "Grasa",
    "goal": "Objetivo",
    "current": "Actual",
    "log_food": "Registrar Comida",
    "start_workout": "Iniciar Entrenamiento",
    "weight": "Peso",
    "sets": "Series",
    "reps": "Repeticiones",
    "rest": "Descanso",
    "completed": "Completado",
    "save": "Guardar",
    "cancel": "Cancelar",
    "submit": "Enviar",
    "loading": "Cargando...",
    "welcome": "Bienvenido a TrainPro",
    "sign_in": "Iniciar Sesión",
    "sign_up": "Registrarse",
    "email": "Correo",
    "password": "Contraseña",
    "name": "Nombre",
    "language": "Idioma",
    "theme": "Tema",
    "light": "Claro",
    "dark": "Oscuro"
  },
  ja: {
    "dashboard": "ダッシュボード",
    "nutrition": "栄養",
    "training": "トレーニング",
    "reports": "レポート",
    "profile": "プロフィール",
    "calories": "カロリー",
    "protein": "プロテイン",
    "carbs": "炭水化物",
    "fat": "脂質",
    "goal": "目標",
    "current": "現在",
    "log_food": "食事記録",
    "start_workout": "ワークアウト開始",
    "weight": "重量",
    "sets": "セット",
    "reps": "レップ",
    "rest": "休憩",
    "completed": "完了",
    "save": "保存",
    "cancel": "キャンセル",
    "submit": "送信",
    "loading": "読み込み中...",
    "welcome": "TrainProへようこそ",
    "sign_in": "サインイン",
    "sign_up": "サインアップ",
    "email": "メール",
    "password": "パスワード",
    "name": "名前",
    "language": "言語",
    "theme": "テーマ",
    "light": "ライト",
    "dark": "ダーク"
  },
  "zh-CN": {
    "dashboard": "仪表板",
    "nutrition": "营养",
    "training": "训练",
    "reports": "报告",
    "profile": "个人资料",
    "calories": "卡路里",
    "protein": "蛋白质",
    "carbs": "碳水化合物",
    "fat": "脂肪",
    "goal": "目标",
    "current": "当前",
    "log_food": "记录食物",
    "start_workout": "开始锻炼",
    "weight": "重量",
    "sets": "组",
    "reps": "次",
    "rest": "休息",
    "completed": "已完成",
    "save": "保存",
    "cancel": "取消",
    "submit": "提交",
    "loading": "加载中...",
    "welcome": "欢迎使用TrainPro",
    "sign_in": "登录",
    "sign_up": "注册",
    "email": "邮箱",
    "password": "密码",
    "name": "姓名",
    "language": "语言",
    "theme": "主题",
    "light": "浅色",
    "dark": "深色"
  },
  de: {
    "dashboard": "Dashboard",
    "nutrition": "Ernährung",
    "training": "Training",
    "reports": "Berichte",
    "profile": "Profil",
    "calories": "Kalorien",
    "protein": "Protein",
    "carbs": "Kohlenhydrate",
    "fat": "Fett",
    "goal": "Ziel",
    "current": "Aktuell",
    "log_food": "Essen Protokollieren",
    "start_workout": "Training Starten",
    "weight": "Gewicht",
    "sets": "Sätze",
    "reps": "Wiederholungen",
    "rest": "Pause",
    "completed": "Abgeschlossen",
    "save": "Speichern",
    "cancel": "Abbrechen",
    "submit": "Senden",
    "loading": "Laden...",
    "welcome": "Willkommen bei TrainPro",
    "sign_in": "Anmelden",
    "sign_up": "Registrieren",
    "email": "E-Mail",
    "password": "Passwort",
    "name": "Name",
    "language": "Sprache",
    "theme": "Design",
    "light": "Hell",
    "dark": "Dunkel"
  },
  "zh-TW": {
    // Common
    "dashboard": "儀表板",
    "nutrition": "營養",
    "training": "訓練", 
    "reports": "報告",
    "profile": "個人資料",
    "calories": "卡路里",
    "protein": "蛋白質",
    "carbs": "碳水化合物",
    "fat": "脂肪",
    "goal": "目標",
    "current": "當前",
    "log_food": "記錄食物",
    "start_workout": "開始鍛鍊",
    "weight": "重量",
    "sets": "組",
    "reps": "次",
    "rest": "休息",
    "completed": "已完成",
    "save": "儲存",
    "cancel": "取消",
    "submit": "提交",
    "loading": "載入中...",
    "welcome": "歡迎使用TrainPro",
    "sign_in": "登入",
    "sign_up": "註冊",
    "email": "電子信箱",
    "password": "密碼",
    "name": "姓名",
    "language": "語言",
    "theme": "主題",
    "light": "淺色",
    "dark": "深色",
    
    // Navigation
    "home": "首頁",
    "overview": "總覽",
    "progress": "進度",
    "analysis": "分析",
    "settings": "設定",
    "exercises": "練習",
    "templates": "範本",
    "sessions": "訓練",
    "history": "歷史",
    "favorites": "我的最愛",
    "search": "搜尋",
    "filter": "篩選",
    
    // Training
    "workout": "健身",
    "exercise": "動作",
    "muscle_groups": "肌群",
    "volume": "訓練量",
    "intensity": "強度",
    "frequency": "頻率",
    "auto_regulation": "自動調節",
    "pump_quality": "泵感品質",
    "fatigue_level": "疲勞程度",
    "muscle_soreness": "肌肉痠痛",
    "recovery": "恢復",
    "progression": "進步",
    "template": "範本",
    "create_template": "建立範本",
    "edit_template": "編輯範本",
    "delete_template": "刪除範本",
    "start_session": "開始訓練",
    "end_session": "結束訓練",
    "pause_session": "暫停訓練",
    "resume_session": "繼續訓練",
    "rest_timer": "休息計時器",
    "next_set": "下一組",
    "previous_set": "上一組",
    "add_set": "新增組數",
    "remove_set": "移除組數",
    "bodyweight": "體重",
    "warmup": "熱身",
    "working_set": "正式組",
    "drop_set": "遞減組",
    "failure": "力竭",
    "rpe": "自覺強度",
    "1rm": "1RM最大重量",
    "volume_landmarks": "訓練量指標",
    "mesocycle": "訓練週期",
    "periodization": "週期化",
    
    // Nutrition  
    "macros": "巨量營養素",
    "calories_burned": "消耗卡路里",
    "calories_consumed": "攝取卡路里",
    "protein_goal": "蛋白質目標",
    "carb_goal": "碳水化合物目標", 
    "fat_goal": "脂肪目標",
    "meal": "餐點",
    "breakfast": "早餐",
    "lunch": "午餐",
    "dinner": "晚餐",
    "snack": "點心",
    "food_diary": "飲食日記",
    "add_food": "新增食物",
    "log_meal": "記錄餐點",
    "nutrition_facts": "營養成分",
    "serving_size": "份量",
    "total_calories": "總卡路里",
    "remaining_calories": "剩餘卡路里",
    "macro_breakdown": "巨量營養素分佈",
    "daily_goals": "每日目標",
    "weekly_goals": "每週目標",
    "nutrition_summary": "營養總結",
    "calorie_deficit": "卡路里赤字",
    "calorie_surplus": "卡路里盈餘",
    "maintenance_calories": "維持卡路里",
    "tdee": "每日總能量消耗",
    "bmr": "基礎代謝率",
    
    // Progress & Analytics
    "body_metrics": "身體指標",
    "body_fat": "體脂率",
    "muscle_mass": "肌肉量",
    "measurements": "圍度測量",
    "photos": "進度照片",
    "weight_change": "體重變化",
    "strength_gains": "力量增長",
    "volume_progression": "訓練量進展",
    "consistency": "一致性",
    "adherence": "遵循度",
    "trends": "趨勢",
    "weekly_summary": "週總結",
    "monthly_summary": "月總結",
    "performance_metrics": "表現指標",
    "recovery_metrics": "恢復指標",
    "nutrition_consistency": "營養一致性",
    "training_consistency": "訓練一致性",
    
    // Feedback & UI
    "excellent": "優秀",
    "good": "良好", 
    "moderate": "中等",
    "poor": "較差",
    "very_poor": "很差",
    "increase": "增加",
    "decrease": "減少",
    "maintain": "維持",
    "too_high": "過高",
    "too_low": "過低",
    "optimal": "最佳",
    "warning": "警告",
    "error": "錯誤",
    "success": "成功",
    "info": "資訊",
    "confirm": "確認",
    "yes": "是",
    "no": "否",
    "ok": "確定",
    "close": "關閉",
    "back": "返回",
    "next": "下一步",
    "previous": "上一步",
    "finish": "完成",
    "edit": "編輯",
    "delete": "刪除",
    "add": "新增",
    "remove": "移除",
    "update": "更新",
    "refresh": "重新整理",
    "sync": "同步",
    "export": "匯出",
    "import": "匯入",
    "share": "分享",
    "copy": "複製",
    "paste": "貼上",
    "cut": "剪下",
    "undo": "復原",
    "redo": "重做",
    "select_all": "全選",
    "clear": "清除",
    "reset": "重設",
    "apply": "套用",
    "preview": "預覽",
    "view": "檢視",
    "hide": "隱藏",
    "show": "顯示",
    "expand": "展開",
    "collapse": "收合",
    "minimize": "最小化",
    "maximize": "最大化",
    "fullscreen": "全螢幕",
    "exit_fullscreen": "退出全螢幕",
    "zoom_in": "放大",
    "zoom_out": "縮小",
    "fit_to_screen": "適合螢幕",
    "print": "列印",
    "download": "下載",
    "upload": "上傳",
    "drag_and_drop": "拖曳放置",
    
    // Additional UI
    "quick_actions": "快速操作",
    "common_tasks": "常用功能",
    "continue_workout": "繼續訓練",
    "recent_activity": "最近活動",
    "your_latest_updates": "最新動態",
    "logged_food": "記錄食物",
    "today": "今天",
    "yesterday": "昨天",
    "about": "約",
    "hours_ago": "小時前",
    "minutes_ago": "分鐘前",
    "view": "檢視",
    "overview": "總覽",
    "macro_breakdown": "巨量營養素分佈",
    "training_progress": "訓練進度",
    "analytics": "分析",
    "activity": "活動",
    "profile_level": "檔案等級",
    "body_fat": "體脂率",
    "latest_entry": "最新記錄",
    "this_week": "本週",
    "volume": "訓練量",
    "total_sessions": "總訓練次數",
    "total_volume": "總訓練量",
    "average_session_time": "平均訓練時間"
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("trainpro-language") as Language;
      if (stored && translations[stored]) return stored;
      
      // Detect browser language
      const browserLang = navigator.language.toLowerCase();
      if (browserLang.startsWith("es")) return "es";
      if (browserLang.startsWith("ja")) return "ja";
      if (browserLang.startsWith("zh-cn") || browserLang === "zh") return "zh-CN";
      if (browserLang.startsWith("de")) return "de";
      if (browserLang.startsWith("zh-tw")) return "zh-TW";
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("trainpro-language", lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}